name: Deploy to EC2

on:
  push:
    branches:
      - main
 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Build and run application
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/aws-instance
            sudo docker build -t aws-instance:latest -f dockerfile .
            sudo docker stop aws-instance || true
            sudo docker rm aws-instance || true
            sudo docker run -d --name aws-instance --restart unless-stopped -p 3000:3000 aws-instance:latest

