name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            APP_DIR=""
            if [ -d "/aws-instance" ]; then
              APP_DIR="/aws-instance"
            elif [ -d "$HOME/aws-instance" ]; then
              APP_DIR="$HOME/aws-instance"
            elif [ -d "/home/ubuntu/aws-instance" ]; then
              APP_DIR="/home/ubuntu/aws-instance"
            else
              echo "aws-instance directory not found on host"
              exit 1
            fi

            git config --global --add safe.directory "$APP_DIR"
            cd "$APP_DIR"
            git pull
            sudo docker compose down
            sudo docker compose up -d --build
            
